// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpvjohywtwrgnqnyyxae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwdmpvaHl3dHdyZ25xbnl5eGFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcyODU2NjYsImV4cCI6MjA5Mjg2MTY2Nn0.NacBdxnUhoIECCixO0U1tQzvJaSDW_nfJtJj89g2pwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});